### ISSUE TITLE
Add --overflow-list-size setting 

### ISSUE THREAD

**Issue by rernst** [CuppenResearch/IAP#32]
Add --overflow-list-size setting to markdup jobs -> make it an option in the ini files.

**Comment by stefvanlieshout** [comment]
Hey Robert, would help me a lot if this was a setting in the ini config file. Just had the same "too many open files" error again with a new installation of the pipeline, so currently have to manually adjust this in the code everytime I update the pipeline.. And perhaps set the default to higher anyway? The amount of data will only increase anyway ;)

**Comment by rernst** [comment]
This will come in the next release (after 1.3). Because of diagnostic validation I can't add it to the upcoming release. Feel free to submit a pull request to develop though.
