### ISSUE TITLE
gc_bias statistics fails to run on large bams.

### ISSUE THREAD

**Issue by inijman** [CuppenResearch/IAP#33]
From the multiplemetrics, big (>100x WGS) bam files yield empty gc_bias result files, stopping the poststats routine.

Apparently, it's a known bug, so we need to upgrade.

c0f5418 Ran into a bug in CollectGcBias with a 100X coverage genome where
    the number of aligned reads was greater than MAX_INT. In the previous
    version, the metrics were only calculated and written out if
    totalAlignedReads was >0. Because of the overflow, totalAlignedReads was a
    random negative number, and thus no metrics were output. To address this,
    I've changed totalAlignedReads to a long and I've changed the if statement
    to skip only if totalAlignedReads==0. I was going to remove the
    totalAlignedReads>=0 check completely and the reason I did not is because
    some tests were not passing due to no reads being added to a level of
    collection despite the collection level being specified in the header and
    thus some things were still assigned to null causing failures. I am not
    sure if this situation would ever come up in production, so I am not 100%
    sure that the check should remain. Open to suggestion.

**Comment by rernst** [comment]
Version v1.141 should contain a fix, see: https://github.com/broadinstitute/picard/pull/321 and https://github.com/broadinstitute/picard/releases/download/1.141/README.txt 

I have installed it on the hpc so we can test it: /hpc/cog_bioinf/common_scripts/picard-tools-1.141/. @stefvanlieshout can you also test the new version?

**Comment by stefvanlieshout** [comment]
Thanks Robert for looking into it, I've installed v1.141 too and will let you know.

**Comment by inijman** [comment]
Voordat we blind overstappen graag ook even goed terug kijken of alle resultaten van de andere onderdelen identiek/vergelijkbaar zijn. Even het idee van validatie laten doorwerken.

Gr ies

**Comment by stefvanlieshout** [comment]
Doe ik. Maar wel even met de kleine testset, anders zit ik weer 5 dagen een crunch te misbruiken ;)
