### ISSUE TITLE
hardcoded link in illumina_vcfutils.pm

### ISSUE THREAD

**Issue by melferink** [CuppenResearch/IAP#35]
Ik zie een hardcoded link naar plink in module illumina_vcfutils.pm.
print VCFUTILS_SH "/hpc/local/CentOS6/cog_bioinf/plink_1.9b3/plink -bfile gender_check --check-sex\n";

Graag plink als input parameter opnemen in de INI file(s).

**Comment by rernst** [comment]
Probably have to change plink_path in ini file to: /hpc/local/CentOS6/cog_bioinf/plink_1.9b3/
