### ISSUE TITLE
duplicate mark resource requests for deep sequenced samples

### ISSUE THREAD

**Issue by hinri** [CuppenResearch/IAP#37]
Sambamba seems to have an increasing memory demand for duplicate marking in deep sequence samples.
The resource requirements for dupmarking do no longer match those for the mapping and should be specified separately. 
Also --overflow-list-size needs tuning or sambamba exceeds the maximum number of (tmp) files that it is allowed to open (and is subsequently killed by the OS)
Sambamba seems to exit with status 0 when memory requirements are not fulfilled.

**Comment by rernst** [comment]
For overflow-list-size see: https://github.com/CuppenResearch/IAP/commit/08926089b73395f1a97a67125eef4fb1d2b688fc

Feel free to add an option specifying markdup memory.
