### ISSUE TITLE
Add softclipping of realigned.bam

### ISSUE THREAD

**Issue by melferink** [CuppenResearch/IAP#5]
/hpc/cog_bioinf/common_scripts/bamUtil/bin/bam clipOverlap --in $bam --out $softclippedbam

**Comment by rernst** [comment]
@melferink Wat is de status hier van?

**Comment by melferink** [comment]
Please remove issue.

Softclipping with bamUtil corrupts BAM file. GATK does not take softclip bases into account for variant calling.

Moreover softclip bases are used in several SV/CNV tools, so it is not preferred to remove soft clip bases from BAM.
