### ISSUE TITLE
VCFutils  output name kinship file

### ISSUE THREAD

**Issue by melferink** [CuppenResearch/IAP#51]
King output file is wrongly renamed:
> filtered_variants.vcf VCF is used as input, output renamed as .kinship 

Please change into:
print VCFUTILS_SH "cp king.kin0 $opt{OUTPUT_DIR}/$runName.filtered_variants.kinship\n";

**Comment by rernst** [comment]
It is renamed as $runName.kinship because king (or actually vcftools) ignores filter status. Therefore it would not make a lot of sense to call it $runName.filtered_variants.kinship?
