### ISSUE TITLE
PreStats will be marked as 'done' even if it fails

### ISSUE THREAD

**Issue by Seth-Karlo** [CuppenResearch/IAP#67]
There is no logic in the script generated here:
https://github.com/CuppenResearch/IAP/blob/master/illumina_prestats.pm#L47

So if the fastqc process fails a subsequent run of the pipeline will skip it.

**Comment by rernst** [comment]
There is logic as this was originally implemented to check whether the job does not get aborted by our cluster. But your right I does not check whether fastqc it self finishes correctly.

**Comment by Seth-Karlo** [comment]
Would checking the exit code of the FastQC process work?

**Comment by rernst** [comment]
That could work, we actually don't use it in the IAP, but it could be a nice solution.

**Comment by rernst** [comment]
I just committed some improvements on checking the prestats results. Unfortunately exit status can not be used as fastqc will sometimes exit with 0, eventhough it did not finish properly.
