### ISSUE TITLE
Software license

### ISSUE THREAD

**Issue by roelj** [CuppenResearch/IAP#82]
Could you clarify under which license conditions this code may be used?

For this, it is customary to add a `LICENSE` file to the root of the project, and add copyright statements to the beginning of each code file.

**Comment by rernst** [comment]
I have added a LICENSE file to the dev branch (will be pushed to master in the next release after 2.3.0): ab08a93d275c46d0bdaf488eda7a8293ec318f40

I will also add one to bamMetrics, but I think there are more repo's here without a license, I think we use MIT most of the time.
