### ISSUE TITLE
Running manta on previously finished run

### ISSUE THREAD

**Issue by sawibo** [CuppenResearch/IAP#86]
The script that fires of the manta jobs only seems to be looking for *dedup.bam and not for *realigned.bam files. This causes problem when running manta on a previously finished run.

**Comment by rernst** [comment]
Did you set realignment to 'no' ? 
my $sample_bam = "$opt{OUTPUT_DIR}/$sample/mapping/$opt{BAM_FILES}->{$sample}"; 
This should use the realigned bam if it is set to yes.

**Comment by sawibo** [comment]
Ah, ofcourse thanks!
